### PR TITLE
fix: @parcel/source-map default import

### LINKED ISSUE #155: SourceMapNode is not a constructor
This is similar to #150

You have the following code in `estransform`:

```js
// packages/estransform/lib/sourcemaps.js
import sourceMapDefault from '@parcel/source-map';

const { default: SourceMapNode } = sourceMapDefault;
```

which breaks when used in Node, because default export is already an object `SourceMapNode`, so extra destructuring makes it undefined leading to

```
TypeError: SourceMapNode is not a constructor
```

If I understood correctly from you previous answer, you have a browser ESM usage mainly, not Node like in my case.
Probably you have some compatibility mode for default exports which makes it work like this.

The original package has only regular default export https://cdn.jsdelivr.net/npm/@parcel/source-map@2.1.1/index.d.ts, so I think it's worth supporting such usage.

### PR DESCRIPTION
**Pull request by bashmish**
Fixes #155

### CODE REVIEW

File: packages/estransform/lib/sourcemaps.js [hunk 1]
```diff
@@ -17,6 +15,10 @@ const SOURCEMAP_REGEX = /(?:(\/\*+\s*?sourceMappingURL\s*=)([\s\S]*?)(\*\/))|(?:
  * @property {string} [file]
  */
 
+/**
+ * @typedef {import('@parcel/source-map').default} SourceMapNode
+ */
+
```
Comment (bashmish) [inline packages/estransform/lib/sourcemaps.js:21]: for some reason it doesn't work without explicit typedef like that and I get

```
packages/estransform/lib/parser.js:126:53 - error TS2345: Argument of type '{ sources: readonly string[]; sourcesContent?: readonly (string | null)[] | undefined; names: readonly string[]; mappings: string; version: number; file?: string | undefined; sourceRoot?: string | undefined; } | SourceMap' is not assignable to parameter of type 'SourceMap'.
  Type '{ sources: readonly string[]; sourcesContent?: readonly (string | null)[] | undefined; names: readonly string[]; mappings: string; version: number; file?: string | undefined; sourceRoot?: string | undefined; }' is not assignable to type 'SourceMap'.
    Types of property 'sources' are incompatible.
      The type 'readonly string[]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.

126                         code: inlineSourcemap(code, map),
```

I tried to play with types a bit, remove `@typedef {Object} SourceMap`, use original `VLQMap` which it looks to be and in other place use the class type itself, but it's a bit of a rabbit hole with new errors popping up on the go

maybe I just don't fully understand how you process source maps, but in any case I hope the removal of types from `packages/estransform/modules.d.ts` is already an improvement

File: packages/estransform/lib/sourcemaps.js [hunk 2]
```diff
@@ -1,8 +1,6 @@
 import { readFile } from 'fs/promises';
 import path from 'path';
-import sourceMapDefault from '@parcel/source-map';
-
-const { default: SourceMapNode } = sourceMapDefault;
+import SourceMapNode from './parcel-source-map-default.cjs';
```
Comment (bashmish) [inline packages/estransform/lib/sourcemaps.js:3]: this workaround is suggested in https://github.com/evanw/esbuild/issues/532
and it's similar to another one you use in `packages/rna-storybook/lib/csf-tools.cjs`

File: packages/estransform/lib/parcel-source-map-default.cjs [hunk 3]
```diff
@@ -0,0 +1,3 @@
+// we need to require the module for compatibility with the default export
+// eslint-disable-next-line @typescript-eslint/no-var-requires
+module.exports = require('@parcel/source-map').default;
```
Comment (bashmish) [inline packages/estransform/lib/parcel-source-map-default.cjs:3]: this workaround is suggested in https://github.com/evanw/esbuild/issues/532
and it's similar to another one you use in `packages/rna-storybook/lib/csf-tools.cjs`

File: packages/estransform/build.js [hunk 4]
```diff
@@ -12,4 +12,9 @@ esbuild.build({
     external: [
         '@parcel/source-map',
     ],
+    banner: {
+        js: `import { createRequire as __moduleCreateRequire } from 'module';
+const require = __moduleCreateRequire(import.meta.url);
+`,
+    },
```
Comment (bashmish) [inline packages/estransform/build.js:19]: I used `npm run build` as a way to test this PR and this is how I found out that this `require` is needed in the new output

any other tests I can run? I didn't understand it from `package.json` or docs

I tested on my side and the new dist works

**Comment by bashmish** [comment]
@edoardocavazza I'd really appreciate if you can review this :)

File: packages/estransform/lib/sourcemaps.js (hunk 2 above)
Comment (edoardocavazza) [inline packages/estransform/lib/sourcemaps.js:3]: I am wondering if we can use the require statement directly in this file, instead of creating .cjs file and build-time banner. I think something like this would work:

```js
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const SourceMapNode = require('@parcel/source-map').default;
```

**Review by edoardocavazza — CHANGES_REQUESTED** [review]
Thanks for your contribution! I have proposed a change that should work the same way, but with (IMO) less complexity.

File: packages/estransform/lib/sourcemaps.js (hunk 2 above)
Comment (bashmish) [reply packages/estransform/lib/sourcemaps.js]: great suggestion, it does work, solves types issue and I tested it in my project where it works too!
I pushed the update

File: packages/estransform/lib/sourcemaps.js (hunk 1 above)
Comment (bashmish) [reply packages/estransform/lib/sourcemaps.js]: fixed by using https://github.com/chialab/rna/pull/157/files#r1314634375

**Comment by bashmish** [comment]
@edoardocavazza fixed as per your suggestion in https://github.com/chialab/rna/pull/157/files#r1314634375, thanks!

**Review by edoardocavazza — APPROVED** [review]
